name: Create release from tag

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Create release
        run: gh release create --repo ${{ github.repository }} ${{ github.ref_name }} original.txt
        env:
          GH_TOKEN: ${{ github.token }}
